# Generated by Django 4.1 on 2022-08-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animals',
            new_name='group',
        ),
    ]
