# Generated by Django 4.1 on 2022-08-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age_in_dog_years',
        ),
    ]
